<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-d7cc41
Date:    2018-09-13 15:29:45
Version: v2.1.4
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-d7cc41",
    "email": {
        "to": "",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:c4941",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": false,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Carrier SCAC",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "ANSR",
                        "checked": false
                    },
                    {
                        "label": "CDNK",
                        "checked": false
                    },
                    {
                        "label": "CRST",
                        "checked": false
                    },
                    {
                        "label": "DART",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "EPES",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "FLXY",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "GDSD",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "HAEI",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "ISCO",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "HJBI",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "KNIG",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "MMTS",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "METR",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "NAVE",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "NRT_SCAC",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "PAMT",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "PREM",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "RVTS",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "SCNN",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "SWFT",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "TCAM",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "USXP",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "USIT",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "WALZ-B",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "WERN",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "WSXI",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "XPOG",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Details",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f7",
            "cid": "c41"
        },
        {
            "label": "Trailer#",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f8",
            "cid": "c46"
        },
        {
            "label": "TJX Shipment# (Ends in M)",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f9",
            "cid": "c51"
        },
        {
            "label": "Number of Cartons",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f10",
            "cid": "c56"
        },
        {
            "label": "Delivery Details",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f11",
            "cid": "c61"
        },
        {
            "label": "Origin (TJX DC)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "H881",
                        "checked": false
                    },
                    {
                        "label": "H882",
                        "checked": false
                    },
                    {
                        "label": "H884",
                        "checked": false
                    },
                    {
                        "label": "H885",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "H887",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "881",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "883",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "886",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "887",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "888",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "893",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "894",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "896",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "897",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "898",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f12",
            "cid": "c66"
        },
        {
            "label": "Destination (Premier SC)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    },
                    {
                        "label": "Monroe, MI",
                        "value": null,
                        "checked": false
                    },
                    {
                        "label": "Montgomery, AL",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "University Park, IL",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f16",
            "cid": "c59"
        },
        {
            "label": "ETA Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c76"
        },
        {
            "label": "ETA Time",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f15",
            "cid": "c81"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class